# Generated by Django 2.2.20 on 2022-01-28 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_bussiness_phonrnumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bussiness',
            old_name='phonrnumber',
            new_name='phonenumber',
        ),
    ]
