# Generated by Django 2.2.20 on 2022-01-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20220128_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bussiness',
            name='type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
