# Generated by Django 2.2.20 on 2022-01-29 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20220129_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bussiness',
            name='bussiness_name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='bussiness',
            name='location',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='employee_name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='jobname',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='location',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='notification',
            name='subject',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='profile',
            name='panchayath',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='second_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
